Fix error in Django 5.2
Using this package in django 5.2 throws this error, since it looks like this warning module
was removed.
```
File "ve/lib64/python3.13/site-packages/lti_authentication/backends.py", line 7, in <module>
  from django.utils.deprecation import RemovedInDjango50Warning  # type: ignore
ImportError: cannot import name 'RemovedInDjango50Warning' from 'django.utils.deprecation' (ve/lib64/python3.13/site-packages/django/utils/deprecation.py)
```

This change adds a graceful fallback for this code.